// The Hermes Agent mascot as 1-bit bitmaps (generated by `hermes-gadget face`; see docs/faces.md).
#pragma once

#include <cstdint>

namespace hg::mascot {

enum class Frame : uint8_t { Idle, Blink, Talk };

// Square, row-major, MSB-first, rows padded to whole bytes. A set bit is ink
// (the white artwork); clear bits are transparent.
struct Bitmap {
  uint16_t size;
  Frame frame;
  const uint8_t* bits;

  bool ink(int x, int y) const {
    const int stride = (size + 7) / 8;
    return (bits[y * stride + (x >> 3)] >> (7 - (x & 7))) & 1;
  }
};

// The largest bitmap of `frame` no bigger than `max_size` (the smallest one
// if none fits).
const Bitmap* pick(int max_size, Frame frame);

// Feature positions in thousandths of the bitmap size, for UI effects.
struct Point {
  int16_t x, y;
};
struct Anchors {
  Point ear_cup;         // headphone cup: "listening" waves start here
  Point mouth;           // "speaking" waves
  Point head_top_right;  // "thinking" dots
  int16_t eyes_y0, eyes_y1;    // rows that change when blinking
  int16_t mouth_y0, mouth_y1;  // rows that change when talking
  // Which way the waves face: 1 to the right, -1 to the left. The shipped
  // mascot listens to the right and speaks to the left; a face looking the
  // other way turns them round.
  int8_t listen_dir = 1;
  int8_t talk_dir = -1;
};
const Anchors& anchors();

}  // namespace hg::mascot
